FROM ubuntu:plucky

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        texlive-latex-base \
        texlive-extra-utils \
        texlive-latex-recommended \
        pdftk
